{{- if .Values.ampere.ingress.enabled -}}
{{- $fullName := include "bangdb-chart.ampere.fullname" . -}} 
{{- $svcPort := .Values.ampere.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "bangdb-chart.labels" . | indent 4 }}
  {{- with .Values.ampere.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ampere.ingress.tls }}
  tls:
  {{- range .Values.ampere.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ampere.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ include "bangdb-chart.fullname" . }}-{{ .Values.ampere.name }}-service
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
