{{- if .Values.ampere.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bangdb-chart.fullname" . }}-{{ .Values.ampere.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bangdb-chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bangdb-chart.name" . }}-{{ .Values.ampere.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.ampere.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bangdb-chart.name" . }}-{{ .Values.ampere.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: ampere-ssl
          secret:
            secretName: ampere-ssl
      {{- with .Values.ampere.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "bangdb-chart.serviceAccountName.ampere" . }}
      {{- with .Values.ampere.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ampere.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ampere.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ampere
          image: "{{ .Values.ampere.image.repository }}:{{ .Values.ampere.image.tag }}"
          imagePullPolicy: {{ .Values.ampere.image.pullPolicy | quote }}
          env:
{{ toYaml .Values.ampere.env | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 90
          volumeMounts:
            - name: ampere-ssl
              mountPath: {{ .Values.ampere.secrets.mountPath }}
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
{{ toYaml .Values.ampere.resources | indent 12 }}
          ports:
            - containerPort: 3000
              name: http
{{- end }}
    
