{{- if and .Values.ampere.serviceAccount.create .Values.ampere.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bangdb-chart.serviceAccountName.ampere" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
{{ include "bangdb-chart.labels" . | indent 4 }}
{{- end -}}
