{{- if .Values.userservice.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bangdb-chart.userservice.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bangdb-chart.labels" . | indent 4 }}
{{- end -}}
