apiVersion: v1
kind: Service
metadata:
  name: {{ include "bangdb-chart.fullname" . }}-user-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bangdb-chart.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "bangdb-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.userserviceType }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{range $rangeList := .Values.service.loadBalancerSourceRanges}}
    - {{ $rangeList }}
    {{end}}
  {{end}}
  ports:
    - name: bangdb-http
      port: {{ .Values.service.port18080 }}
      {{- if and .Values.service.httpNodePort (eq .Values.service.userserviceType "NodePort") }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
      protocol: TCP
      targetPort: 18080 