apiVersion: v1
kind: Service
metadata:
  name: {{ include "bangdb-chart.fullname" . }}
  labels:
{{ include "bangdb-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10101
      protocol: TCP
      name: tcp-10101
    - port: {{ .Values.service.port }}
      targetPort: 18080
      protocol: TCP
      name: tcp-18080
  selector:
    app.kubernetes.io/name: {{ include "bangdb-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
