# Default values for bangdb-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

clusterDomain: cluster.local

image:
  repository: bangdb/bangdb-server
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "bangdb-instance"
fullnameOverride: "bangdb"

updateStrategy:
  type: RollingUpdate

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name:

podSecurityContext: {}
  # fsGroup: 1000
  # fsGroupChangePolicy: OnRootMismatch

securityContext:
  enabled: true
  fsGroup: 0
  # fsGroupChangePolicy: OnRootMismatch
  runAsUser: 1000
  # supplementalGroups: [bangdb,1000]
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

persistence:
  enabled: true
  # existingClaim:
  mountPathdata: /bangdb_2.0_ubuntu18/bin/data
  mountPathlogdir: /bangdb_2.0_ubuntu18/bin/logdir
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

service:
  type: ClusterIP
  port10101: 10101
  port18080: 18080


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ampere:
  enabled: true
  name: ampere
  serviceAccount:
  # Specifies whether a service account should be created
    create: false
    name:
  replicas: 1
  imagePullSecrets: []
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: test.local
        paths: []
    tls: []
  service:
    port: 443
    serviceType: NodePort
    httpsNodePort: 30920
    loadBalancerIP: {}
    loadBalancerSourceRanges: {}
  securityContext:
    enabled: false
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsUser: 1000
    supplementalGroups: ["apprunner"]
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  image:
    repository: bangdb/bangdb-ampere
    tag: latest
    pullPolicy: Always
  nodeSelector: {}
  tolerations: []
  affinity: {}
  antiAffinity: "soft"
  updateStrategy:
    type: RollingUpdate
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
