# Default values for bangdb-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

clusterDomain: cluster.local

image:
  repository: bangdb/bangdb-server
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "bangdb-instance"
fullnameOverride: "bangdb"

secrets:
  mountPath: "/bangdb_2.0_ubuntu18/bin/certificate"

updateStrategy:
  type: RollingUpdate

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  name:

podSecurityContext: {}
  # fsGroup: 1000
  # fsGroupChangePolicy: OnRootMismatch

securityContext:
  enabled: true
  fsGroup: 0
  # fsGroupChangePolicy: OnRootMismatch
  runAsUser: 1000
  # supplementalGroups: [bangdb,1000]
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

persistence:
  enabled: true
  # existingClaim:
  mountPathdata: /bangdb_2.0_ubuntu18/bin/data
  mountPathlogdir: /bangdb_2.0_ubuntu18/bin/logdir
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

service:
  type: ClusterIP
  port10101: 10101
  port18080: 18080
  userserviceType: NodePort
  httpNodePort: 30921
  loadBalancerIP: {}
  loadBalancerSourceRanges: {}


ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

userservice:
  enabled: true
  name: userservice
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  imagePullSecrets: []
  serviceAccount:
    create: true
    name:
  secrets:
    mountPath: "/bangdb_2.0_ubuntu18/bin/certificate"
  image:
    repository: bangdb/bangdb-server
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: test.local
        paths: []
    tls: []
  service:
    type: ClusterIP
    port10101: 10101
    port18080: 18080
    userserviceType: NodePort
    httpNodePort: 30921
    loadBalancerIP: {}
    loadBalancerSourceRanges: {}
  resources: 
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    enabled: true
    fsGroup: 0
    # fsGroupChangePolicy: OnRootMismatch
    runAsUser: 1000
    # supplementalGroups: [bangdb,1000]
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  persistence:
    enabled: true
    # existingClaim:
    mountPathdata: /bangdb_2.0_ubuntu18/bin/data
    mountPathlogdir: /bangdb_2.0_ubuntu18/bin/logdir
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
ampere:
  enabled: true
  name: ampere
  serviceAccount:
  # Specifies whether a service account should be created
    create: true
    name:
  replicas: 1
  imagePullSecrets: []
  secrets:
    mountPath: "/home/node/app/certificate"
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: test.local
        paths: []
    tls: []
  service:
    port: 3000
    serviceType: NodePort
    httpNodePort: 30920
    loadBalancerIP: {}
    loadBalancerSourceRanges: {}
  securityContext:
    enabled: false
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsUser: 1000
    supplementalGroups: ["apprunner"]
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  image:
    repository: bangdb/bangdb-ampere
    tag: latest
    pullPolicy: Always
  nodeSelector: {}
  tolerations: []
  affinity: {}
  antiAffinity: "soft"
  updateStrategy:
    type: RollingUpdate
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  env:
    - name: ANALYZE
      value: "false"
    - name: APP_ENV
      value: "production"
    - name: NEXT_PUBLIC_APPSTORE_URL
      value: "https://userbangdb.bangdb.com:30922"
    - name: USER_API
      value: "userbangdb.bangdb.com:30922"
      # value: "{{ include "bangdb-chart.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port18080 }}"
